name: Test build Storybook

on:
  workflow_call:

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc
    - name: Install dependencies
      run: npm ci
      shell: bash
    - name: Build Storybook
      run: npm run build
      shell: bash
